export enum OcrJobStatus {
  PENDING           = 'PENDING',
  PROCESSING_STARTED = 'PROCESSING_STARTED',
  FETCHING_FILE     = 'FETCHING_FILE',
  EXTRACTING_TEXT   = 'EXTRACTING_TEXT',
  TRANSFORMING_DATA = 'TRANSFORMING_DATA',
  SAVING_DATA       = 'SAVING_DATA',
  COMPLETED         = 'COMPLETED',
  FAILED            = 'FAILED',
}
